// Code generated by protoc-gen-go. DO NOT EDIT.
// source: context.proto

/*
Package limiter is a generated protocol buffer package.

It is generated from these files:
	context.proto

It has these top-level messages:
	Context
*/
package limiter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Limit     int64
// Remaining int64
// Reset     int64
// Reached   bool
type Context struct {
	Limit     string `protobuf:"bytes,1,opt,name=limit" json:"limit,omitempty"`
	Remaining string `protobuf:"bytes,2,opt,name=remaining" json:"remaining,omitempty"`
	Reaset    string `protobuf:"bytes,3,opt,name=reaset" json:"reaset,omitempty"`
	Reached   bool   `protobuf:"varint,4,opt,name=reached" json:"reached,omitempty"`
}

func (m *Context) Reset()                    { *m = Context{} }
func (m *Context) String() string            { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()               {}
func (*Context) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Context) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

func (m *Context) GetRemaining() string {
	if m != nil {
		return m.Remaining
	}
	return ""
}

func (m *Context) GetReaset() string {
	if m != nil {
		return m.Reaset
	}
	return ""
}

func (m *Context) GetReached() bool {
	if m != nil {
		return m.Reached
	}
	return false
}

func init() {
	proto.RegisterType((*Context)(nil), "limiter.Context")
}

func init() { proto.RegisterFile("context.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x49, 0xad, 0x28, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0xc9, 0xcc, 0xcd, 0x2c,
	0x49, 0x2d, 0x52, 0xca, 0xe7, 0x62, 0x77, 0x86, 0xc8, 0x08, 0x89, 0x70, 0xb1, 0x82, 0x45, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x19, 0x2e, 0xce, 0xa2, 0xd4, 0xdc, 0xc4,
	0xcc, 0xbc, 0xcc, 0xbc, 0x74, 0x09, 0x26, 0xb0, 0x0c, 0x42, 0x40, 0x48, 0x8c, 0x8b, 0xad, 0x28,
	0x35, 0xb1, 0x38, 0xb5, 0x44, 0x82, 0x19, 0x2c, 0x05, 0xe5, 0x09, 0x49, 0x70, 0xb1, 0x17, 0xa5,
	0x26, 0x26, 0x67, 0xa4, 0xa6, 0x48, 0xb0, 0x28, 0x30, 0x6a, 0x70, 0x04, 0xc1, 0xb8, 0x49, 0x6c,
	0x60, 0x07, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x0f, 0x52, 0xf1, 0x91, 0x00, 0x00,
	0x00,
}
